In [2]:
from tensorflow.keras.layers import Input,Embedding,Flatten,Dot,Dense
from tensorflow.keras import Model
import pandas as pd
import numpy as np


#### Tutorial Source: https://barnesanalytics.com/deep-learning-based-recommendation-engines-using-keras

In [3]:
df = pd.read_csv('./ratings_small.csv')

In [4]:
df['rating'] = df['rating'].map({1:-1,2:-1,3:0,4:1,5:1,1.5:-1,2.5:-1,3.5:1,4.5:1})

In [9]:
user_input = Input(shape=[1], name="User-Input")
user_embedding = Embedding(len(df.userId.unique())+1, 5, name="User-Embedding")(user_input)
user_vec = Flatten(name="Flatten-users")(user_embedding)

movie_input = Input(shape=[1], name="Movie-Input")
movie_embedding = Embedding(len(df.movieId.unique())+1, 5, name="Movie-Embedding")(movie_input)
movie_vec = Flatten(name="Flatten-movies")(movie_embedding)

prod = Dot(name="Dot-Product", axes=1)([user_vec, movie_vec])
model = Model([user_input, movie_input], prod)
model.compile('adam', 'mean_squared_error')

In [9]:
model.summary()

Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
User-Input (InputLayer)         [(None, 1)]          0                                            
__________________________________________________________________________________________________
Movie-Input (InputLayer)        [(None, 1)]          0                                            
__________________________________________________________________________________________________
User-Embedding (Embedding)      (None, 1, 5)         3360        User-Input[0][0]                 
__________________________________________________________________________________________________
Movie-Embedding (Embedding)     (None, 1, 5)         45335       Movie-Input[0][0]                
______________________________________________________________________________________________

In [5]:
df.userId.unique()

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [43]:
len(df.userId.unique())

671

In [6]:
df.movieId.unique()

array([  31, 1029, 1061, ...,  129, 4736, 6425], dtype=int64)

In [10]:
import numpy as np
model.predict([np.array([610]),np.array([1])])

array([[-0.00178779]], dtype=float32)

In [11]:
model.predict([np.array([175]),np.array([10])])

array([[0.0016412]], dtype=float32)

In [47]:
model.predict([np.array([627]),np.array([200])])

array([[-0.00079337]], dtype=float32)

In [12]:
model.predict([np.array([671]),np.array([4736])])

array([[0.00346424]], dtype=float32)